"""Add 2FA fields to User model

Revision ID: 6e7de23ba080
Revises: 740cef49289b
Create Date: 2024-12-04 23:39:28.064907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7de23ba080'
down_revision: Union[str, None] = '740cef49289b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_qr_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_qr_code')
    # ### end Alembic commands ###
