"""Add 2FA fields to User model

Revision ID: 740cef49289b
Revises: 1e2c676792c5
Create Date: 2024-12-04 23:32:16.668242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740cef49289b'
down_revision: Union[str, None] = '1e2c676792c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_2fa_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_totp_2fa_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('totp_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'is_totp_2fa_enabled')
    op.drop_column('users', 'is_email_2fa_enabled')
    # ### end Alembic commands ###
